// Course faculty roster, ordered alphabetically by first name.
// Photos are stored locally in assets/faculty/ since the source institutions' servers block hotlinked requests.
window.facultyData = {
  faculty: [
    { name: "Billy Quilty", affiliation: "Charité Centre for Global Health", topics: ["Outbreak response", "Vaccines", "Transmission dynamics"], profileUrl: "https://globalhealth.charite.de/en/metas/person/person/address_detail/billy_quilty/", photoUrl: "assets/faculty/billy-quilty.jpeg", bio: "Researcher in infectious disease epidemiology and mathematical modelling at the Charité Centre for Global Health, with a PhD from LSHTM focused on modelling quarantine and testing strategies during the COVID-19 pandemic. His work spans vaccine impact evaluation and social contact pattern analysis, and he retains an honorary research fellowship at LSHTM." },
    { name: "David Hodgson", affiliation: "Charité Centre for Global Health", topics: ["Serology", "Transmission dynamics", "Vaccines"], profileUrl: "https://globalhealth.charite.de/en/metas/person/person/address_detail/dr_david_hodgson", photoUrl: "assets/faculty/david-hodgson.jpg", bio: "Postdoctoral researcher at the Charité Centre for Global Health, developing models that integrate serological data, immunology, and epidemiology to inform vaccination policy. He completed his PhD at LSHTM on transmission modelling and cost-effectiveness of interventions against RSV, work that has informed national immunisation advisory groups." },
    { name: "Frank Sandmann", affiliation: "Robert Koch Institute", topics: ["Health economics", "Vaccines", "Policy"], profileUrl: "https://orcid.org/0000-0001-5641-1931", photoUrl: "assets/faculty/frank-sandmann.jpeg", bio: "Frank is leading the RKI modelling group on immunisation. He is a health economist and mathematical modeller with general research interests in health economic evaluations and healthcare policy to guide evidence-based decision making for infectious as well as non-infectious diseases" },
    { name: "Gesine Meyer-Rath", affiliation: "Boston University School of Public Health / HE2RO, University of the Witwatersrand", topics: ["Health economics", "Policy", "Model evaluation"], profileUrl: "https://www.bu.edu/sph/profile/gesine-meyer-rath/", photoUrl: "assets/faculty/gesine-meyer-rath.jpg", bio: "Research Associate Professor in the Department of Global Health at Boston University School of Public Health and Principal Researcher at the Health Economics and Epidemiology Research Office (HE2RO). She is a physician and health economist working on the economics of HIV, TB, and COVID-19 in low- and middle-income countries, with a focus on modelling methods for economic evaluation." },
    { name: "Hugo Soubrier", affiliation: "Charité Centre for Global Health", topics: ["Outbreak response", "Data analytics", "Transmission dynamics"], profileUrl: "https://globalhealth.charite.de/en/metas/person/person/address_detail/hugo_soubrier/", photoUrl: "assets/faculty/hugo-soubrier.png", bio: "PhD candidate at the Charité Centre for Global Health, co-supervised by Prof. Stefan Flasche, Anton Camacho (Epicentre), and Olivier le Polain (WHO). His research applies mathematical and data analytics approaches to outbreak response and epidemiology workflows in humanitarian emergencies." },
    { name: "Julia Mayer", affiliation: "Charité Centre for Global Health", topics: ["Vaccines", "Transmission dynamics", "Model choice"], profileUrl: "https://globalhealth.charite.de/en/metas/person/person/address_detail/julia_stephanie_mayer/", photoUrl: "assets/faculty/julia-mayer.jpg", bio: "PhD researcher at the Charité Centre for Global Health, using mathematical modelling to determine optimal vaccination strategies against RSV in children in low- and middle-income countries. She holds a bachelor's degree in bioengineering from EPFL and an MSc in Epidemiology from LSHTM." },
    { name: "Matej Kriznar", affiliation: "Charité Centre for Global Health", topics: ["Phylogenetics", "Data analytics", "Model evaluation"], profileUrl: "https://globalhealth.charite.de/en/metas/person/person/address_detail/matej_kriznar/", photoUrl: "assets/faculty/matej-kriznar.png", bio: "Researcher at the Charité Centre for Global Health working on computational modelling of historical population processes and the robustness of Bayesian phylogenetic methods. His background spans population genetics, computational social science, and pathogen genomics." },
    { name: "Matthieu Domenech de Cellès", affiliation: "Max Planck Institute for Infection Biology, Berlin", topics: ["Transmission dynamics", "Vaccines", "Model choice"], profileUrl: "https://www.mpiib-berlin.mpg.de/1953132/matthieu-domenech-de-cell-s", photoUrl: "assets/faculty/matthieu-domenech-de-celles.jpg", bio: "Max Planck Research Group Leader at the Max Planck Institute for Infection Biology, Berlin. His research uses mathematical modelling to understand the population dynamics of infectious diseases, including bacterial resistance to antibiotics, vaccine impact, and the mechanisms of disease seasonality." },
    { name: "Stefan Flasche", affiliation: "Charité Centre for Global Health", topics: ["Vaccines", "Transmission dynamics", "Policy"], profileUrl: "https://globalhealth.charite.de/en/metas/person/person/address_detail/prof_dr_stefan_flasche/", photoUrl: "assets/faculty/stefan-flasche.png", bio: "Professor at the Charité Centre for Global Health and Honorary Professor at LSHTM. His research focuses on optimising global immunisation strategies, with a longstanding interest in infectious disease transmission dynamics." }
  ]
};
