// Course faculty roster, ordered alphabetically by first name.
// photoUrl is left empty where no reliably hotlinkable portrait was found on the person's profile page.
window.facultyData = {
  faculty: [
    { name: "Billy Quilty", affiliation: "Charité Centre for Global Health", profileUrl: "https://globalhealth.charite.de/en/metas/person/person/address_detail/billy_quilty/", photoUrl: "https://globalhealth.charite.de/fileadmin/_processed_/5/5/csm_Quilty_Billy_photo_cb21c974b8.jpeg", bio: "Researcher in infectious disease epidemiology and mathematical modelling at the Charité Centre for Global Health, with a PhD from LSHTM focused on modelling quarantine and testing strategies during the COVID-19 pandemic. His work spans vaccine impact evaluation and social contact pattern analysis, and he retains an honorary research fellowship at LSHTM." },
    { name: "David Hodgson", affiliation: "Charité Centre for Global Health", profileUrl: "https://globalhealth.charite.de/en/metas/person/person/address_detail/dr_david_hodgson", photoUrl: "https://globalhealth.charite.de/fileadmin/_processed_/5/9/csm_Hodgson_David_photo_3c96c0ae3a.jpg", bio: "Postdoctoral researcher at the Charité Centre for Global Health, developing models that integrate serological data, immunology, and epidemiology to inform vaccination policy. He completed his PhD at LSHTM on transmission modelling and cost-effectiveness of interventions against RSV, work that has informed national immunisation advisory groups." },
    { name: "Gesine Meyer-Rath", affiliation: "Boston University School of Public Health / HE2RO, University of the Witwatersrand", profileUrl: "https://www.bu.edu/sph/profile/gesine-meyer-rath/", photoUrl: "https://www.bu.edu/sph/files/2013/10/Gesine-Meyer-Rath-1.jpg", bio: "Research Associate Professor in the Department of Global Health at Boston University School of Public Health and Principal Researcher at the Health Economics and Epidemiology Research Office (HE2RO). She is a physician and health economist working on the economics of HIV, TB, and COVID-19 in low- and middle-income countries, with a focus on modelling methods for economic evaluation." },
    { name: "Hugo Soubrier", affiliation: "Charité Centre for Global Health", profileUrl: "https://globalhealth.charite.de/en/metas/person/person/address_detail/hugo_soubrier/", photoUrl: "https://globalhealth.charite.de/fileadmin/_processed_/7/9/csm_Portrait_Soubrier_Hugo_a72e438efe.png", bio: "PhD candidate at the Charité Centre for Global Health, co-supervised by Prof. Stefan Flasche, Anton Camacho (Epicentre), and Olivier le Polain (WHO). His research applies mathematical and data analytics approaches to outbreak response and epidemiology workflows in humanitarian emergencies." },
    { name: "Julia Mayer", affiliation: "Charité Centre for Global Health", profileUrl: "https://globalhealth.charite.de/en/metas/person/person/address_detail/julia_stephanie_mayer/", photoUrl: "https://globalhealth.charite.de/fileadmin/_processed_/3/d/csm_Mayer_Julia_0f70fbeea5.jpg", bio: "PhD researcher at the Charité Centre for Global Health, using mathematical modelling to determine optimal vaccination strategies against RSV in children in low- and middle-income countries. She holds a bachelor's degree in bioengineering from EPFL and an MSc in Epidemiology from LSHTM." },
    { name: "Matej Kriznar", affiliation: "Charité Centre for Global Health", profileUrl: "https://globalhealth.charite.de/en/metas/person/person/address_detail/matej_kriznar/", photoUrl: "https://globalhealth.charite.de/fileadmin/_processed_/c/6/csm_Kriznar_Matej_Portrait_4235280d9a.png", bio: "Researcher at the Charité Centre for Global Health working on computational modelling of historical population processes and the robustness of Bayesian phylogenetic methods. His background spans population genetics, computational social science, and pathogen genomics." },
    { name: "Matthieu Domenech de Cellès", affiliation: "Max Planck Institute for Infection Biology, Berlin", profileUrl: "https://www.mpiib-berlin.mpg.de/1953132/matthieu-domenech-de-cell-s", photoUrl: "https://www.mpiib-berlin.mpg.de/2151273/original-1691581725.webp", bio: "Max Planck Research Group Leader at the Max Planck Institute for Infection Biology, Berlin. His research uses mathematical modelling to understand the population dynamics of infectious diseases, including bacterial resistance to antibiotics, vaccine impact, and the mechanisms of disease seasonality." },
    { name: "Stefan Flasche", affiliation: "Charité Centre for Global Health", profileUrl: "https://globalhealth.charite.de/en/metas/person/person/address_detail/prof_dr_stefan_flasche/", photoUrl: "https://globalhealth.charite.de/fileadmin/_processed_/2/2/csm_Prof_Flasche_Picture_e54f08c8cc.png", bio: "Professor at the Charité Centre for Global Health and Honorary Professor at LSHTM. His research focuses on optimising global immunisation strategies, with a longstanding interest in infectious disease transmission dynamics." }
  ]
};
